apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- managedconnectors.cos.bf2.org-v1.yml
- managedconnectorclusters.cos.bf2.org-v1.yml
- kubernetes.yml
- managedconnectoroperators.cos.bf2.org-v1.yml
